### ISSUE TITLE
Separate resolvers ( query, mutation ) logic into separate files

### ISSUE THREAD

**Issue by techyrajeev** [the-road-to-graphql/react-apollo-link-state-example#7]
How can I separate client side resolvers into multiple separate files and later import them in client file ?

e.g in below code all resolvers are written in a single file, for large projects it will be good idea to separate them into multiple contextual files.

```
const toggleSelectRepository = (_, { id, isSelected }, { cache }) => {
  let { selectedRepositoryIds } = cache.readQuery({
    query: GET_SELECTED_REPOSITORIES,
  });

  selectedRepositoryIds = isSelected
    ? selectedRepositoryIds.filter(itemId => itemId !== id)
    : selectedRepositoryIds.concat(id);

  cache.writeQuery({
    query: GET_SELECTED_REPOSITORIES,
    data: { selectedRepositoryIds },
  });

  return { id, isSelected: !isSelected };
};

const stateLink = withClientState({
  cache,
  defaults: initialState,
  resolvers: {
    Mutation: {
      toggleSelectRepository,
    },
  },
});
```

I need help in organising my project structure in scalable and maintainable way.

**Comment by rwieruch** [comment]
Maybe it helps you to checkout this project: https://github.com/the-road-to-graphql/fullstack-apollo-express-postgresql-boilerplate/tree/master/src Here you can see how resolvers and schema are separated by domain (user, message).

**Comment by techyrajeev** [comment]
Thanks a lot @rwieruch. Above project is very well organised. 'graphql-resolver' is what I needed.
